{
    "__default__" :
    {
        "account" : "jandr",
        "time" : "45:00",
        "n" : 1,
         "name"      : "JOBNAME.{rule}.{wildcards}",
        "output"    : "logs/{rule}.{wildcards}.out",
        "error"     : "logs/{rule}.{wildcards}.err", 
        "memory": 500G
    },
    "annotate_snps" :
    {
        "time" : "45:00",
        "memory": 100G
    },
        "taxonomic_filter" :
    {
        "time" : "15:00:00",
        "memory": 500G
    },
            "gatk_call" :
    {
        "time" : "5:00:00",
        "memory": 200G
    },
            "trim_reads" :
    {
        "time" : "2:00:00",
        "memory": 100G
    }


}