## Rule parameters ##
ref:
    ['H37Rv']
mapper: 
    ['bwa']
caller:
    ['gatk']
filter:
    ['qfilt']
depth_filter:
    ['5']
qual_filter:
    ['30'] 
fastq1_suffix:
    '_R1_001.fastq.gz'
fastq2_suffix:  
    '_R2_001.fastq.gz'

## Locations ##
file_list:
    'config/test_data.tsv'
ref_dir:
    'workflow/refs/'
snpeff:
    '/scg/apps/software/snpeff/4.3t/snpEff/snpEff.jar'
snpeff_db:
    'Mycobacterium_tuberculosis_h37rv'
snpeff_datapath:
    'workflow/refs/snpEff/'
snpeff_configpath:
    'config/snpEff.config'
bed_path:
    'workflow/refs/H37Rv_ppe.bed.gz'
vcf_header:
    'workflow/refs/ppe_hdr.txt'
scripts_dir: 
   'workflow/scripts/'

# Previously run input file lists: 
# samples_df = pd.read_table('config/Stanford_MT01-04.tsv',sep = ',').set_index(["sample","batch"],drop=False)
#samples_df = pd.read_table('config/MT06-2022-03-04_withEnvCult.tsv',sep = ',').set_index(["sample","batch"],drop=False)
#samples_df = pd.read_table('config/pgy.tsv',sep = ',').set_index(["sample","batch"],drop=False)
#samples_df = pd.read_table('config/SU022.tsv',sep = ',').set_index(["sample","batch"],drop=False)
# samples_df = pd.read_table('config/SU025.tsv',sep = ',').set_index(["sample","batch"],drop=False)
# samples_df = pd.read_table('config/SU027.tsv',sep = ',').set_index(["sample","batch"],drop=False)
# samples_df = pd.read_table('config/tgen_samples.tsv',sep = ',').set_index(["sample","batch"],drop=False) # done
# samples_df = pd.read_table('config/tgen_samples2.tsv',sep = ',').set_index(["sample","batch"],drop=False)
# samples_df = pd.read_table('config/tgen_samples3_nodups.tsv',sep = ',').set_index(["sample","batch"],drop=False)
#samples_df = pd.read_table('config/perform.tsv',sep = ',').set_index(["sample","batch"],drop=False)
#samples_df = pd.read_table('config/test_data.tsv',sep = ',').set_index(["sample","batch"],drop=False)